language: python
python:
- 3.6.4
install:
- pip install -r requirements.txt
- pip install braintree coveralls mock mysqlclient
env:
- DB=sqlite
- DB=mysql
- DB=postgres
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hc;'
  - psql -c 'create database hc;' -U postgres
addons:
  postgresql: '9.4'
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py collectstatic --noinput
- coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
notifications:
  slack:
    secure: h3dbHbLPzPf8jae286TyQAKVebK4ywTxxTjFznoExsoJf75lcUS6f80T06iGxuh0dbd94uVr5uEx+LtZlaPODB4a5otaFXMIFuAlkFDpOmqdRoSCZeLvyDiR5JlF6wKcQvJRqonD7kDAAY6NNR8ZRsoE9pVUewhb7AYmwlpUyns7Frd8iZyrW8Gzt3tu7i1lUJIYJ5RW/scJ4r10g+slqpoEKb2pa5LbcBYvK6pug+6AjbvV5xOqSB7ATpNzId8R0CyaXAj/c6ZttCWtL5XLNhOpUDLrmtguULPomGwY1ACAe6PRF2kkP+NtFQMYcdW93pv+p7LSYqcDzxJFXdQe5NPS6Q99rHzuSQoyFQWJdXeAFghgxE3B43g20Gno6OQDOu4lZp9fJom/n9k8ApeCm+xJQVTZHUuUqpRzyBVxJ2PY/IXrcYbhZs1Oe71RxPFn3LeMlBxBVo5SAnr9epMefbUzA50w0/axMqddRZRoccmEuGAabiOhqSHgT/ZDzKBnNk6qDe0WPml2SDwT7zkGvJI6eoIX9BI/56vms8wGkJA1QFx5ZuIFHk4KDJdBlThfK6aEpI22ZXc1mGdvn3v8g8hoev1b37DJAABtrP7b9Zdz/oJWQcaOWlfUMFkqP7uIRvcgvgM+Smi5YSaiTWj0Jbn75GH7D/+mBeYBFtduH/E=
